#include "datawapperegenerator.h"
#include "rapidjson/document.h"

using namespace rapidjson;
extern spdlog::logger *g_logger;

DataWappereGenerator::DataWappereGenerator(const ProtoMessage &msg, string sqlfile):
	m_msg(msg),
	m_bGuardStart(true),
	m_nIdent(0),
	m_bIsMsg(false),
	m_bIsObject(false),
	m_sqlFileName(sqlfile)
{
	memset(m_charArrTmp, 0, 1024);
}

void DataWappereGenerator::GenerateDataWapper()
{
	if(m_msg.name.empty())
	{
		g_logger->info("kb: Nothing to be done");
		return;
	}

	if(m_msg.isNew)
	{
		g_logger->info("kb: already compiled");
		return;
	}

	for(const auto & msg : m_msg.m_VecSubMsg)
	{
		DataWappereGenerator dw(msg);
		dw.GenerateDataWapper();
	}

	struct stat dirInfo;
	if(stat("./include", &dirInfo))
	{
		// dir not exist
		system("mkdir -p ./include");
	}

	string fileName("./include/");
	fileName.append(m_msg.fileName);

	fileName.append(".h");

	m_dstFile.open(fileName.c_str());

	if(!m_dstFile.is_open())
	{
		g_logger->error("open {} failed\n", fileName.c_str());
		return;
	}

	// message has schema
	if(m_msg.fileName.find("msg") != string::npos ||
			m_msg.fileName == "videosliceinfo" ||
			m_msg.fileName == "imageinfo" ||
			m_msg.fileName == "imagelist" ||
			m_msg.fileName == "videoslicelist" ||
			m_msg.fileName == "subscribecancel" ||
			m_msg.fileName == "dispositioncancel")
	{
		m_bIsMsg = true;
	}

	if(m_msg.fileName.find("msg") == string::npos &&
			m_msg.fileName.find("list") == string::npos)
	{
		m_bIsObject = true;
	}

	HeadGuard();
	WriteWithNewLine();

	License();
	WriteWithNewLine();

	Headers();
	WriteWithNewLine();

	Schema();
	WriteWithNewLine();

//	NameSpace();
//	WriteWithNewLine();

	FileStaticVar();
	WriteWithNewLine();

	ClassStart();

	pub();

	TypeDef();
	WriteWithNewLine();

	construct();
	WriteWithNewLine();

	create();
	WriteWithNewLine();

	createWithData();
	WriteWithNewLine();

	destruct();
	WriteWithNewLine();

	Release();
	WriteWithNewLine();

	// experimental
	if(!m_sqlFileName.empty())
	{
		g_logger->info("sql:{}", m_sqlFileName);
		ToCdb();
		WriteWithNewLine();
	}

//	if(m_bIsObject)
//	{
//		ToCdb();
//		WriteWithNewLine();
//	}

	ToString();
	WriteWithNewLine();

	ToStringWriter();
	WriteWithNewLine();

	ToStringByProto();
	WriteWithNewLine();

	ToStringWithSpecifiedField();
	WriteWithNewLine();

	FromString();
	WriteWithNewLine();

//	FromStringNoCheck();
//	WriteWithNewLine();

	FromStringProto();
	WriteWithNewLine();

	Serialize();
	WriteWithNewLine();

	DeSerial();
	WriteWithNewLine();

	ObjectBegin();
	WriteWithNewLine();

	set("bool SetString(hash_t hKey, const char* value, size_t length)", "string");
	WriteWithNewLine();

	set("bool SetNull(hash_t hKey)", "null");
	WriteWithNewLine();

	set("bool SetBool(hash_t hKey, bool value)", "bool");
	WriteWithNewLine();

	set("bool SetInt(hash_t hKey, int64_t value)", "int64");
	WriteWithNewLine();

	set("bool SetDouble(hash_t hKey, double value)", "double");
	WriteWithNewLine();

	getSet();
	WriteWithNewLine();

	if(m_bIsMsg)
	{
		pri();
		InitSchema();
	}

	pri();
	Variable();

	ClassEnd();
	WriteWithNewLine();

	HeadGuard();

	g_logger->info("{} generated", fileName.c_str());

	m_dstFile.close();

	return;
}

void DataWappereGenerator::HeadGuard()
{
	string dst(m_msg.fileName);
	dst.append("_H");
	ToUpperCase(dst);

	if(m_bGuardStart)
	{
		string tmp("#ifndef ");
		tmp.append(dst);
		WriteWithNewLine(tmp);

		tmp = "#define ";
		tmp.append(dst);
		WriteWithNewLine(tmp);

		m_bGuardStart = false;
	}
	else
	{
		Write("#endif");
	}

	return;
}

void DataWappereGenerator::License()
{
	string name(m_msg.fileName);
	name.append(".json");

	sprintf(m_charArrTmp, "// Generated by the kbuf.  DO NOT EDIT!\n"
						  "// source: %s", name.c_str());

	WriteWithNewLine(m_charArrTmp);

	return;
}

void DataWappereGenerator::Headers()
{

	sprintf(m_charArrTmp, "#include \"%s.pb.h\"", m_msg.fileName.c_str());
	WriteWithNewLine(m_charArrTmp);

	WriteWithNewLine("#include <sstream>");

	if(m_bIsMsg)
	{
		WriteWithNewLine("#include <mutex>");
	}

	WriteWithNewLine("#include \"google/protobuf/util/json_util.h\"");
	WriteWithNewLine("#include \"viidbasedata.h\"");
	WriteWithNewLine("#include \"viidjsonreadhandler.h\"");

	for(const auto & submsg : m_msg.m_VecSubMsg)
	{
		string hd = submsg.fileName;
		string usrHd("#include \"");
		usrHd.append(hd);
		usrHd.append(".h\"");
		WriteWithNewLine(usrHd);
	}

	return;
}

void DataWappereGenerator::Schema()
{
	// message has schema
	if(!m_bIsMsg)
	{
		return;
	}

	char tmp[1024*1024*2] = {0};
	string schema = TextToCpp(m_msg.m_strSchema);

	sprintf(tmp,"static const char* g_str%sSchema =\n%s;",
			m_msg.name.c_str(),
			schema.c_str()
			);

	WriteWithNewLine(tmp);
}

void DataWappereGenerator::NameSpace()
{
	WriteWithNewLine("using namespace google::protobuf::util;");
	WriteWithNewLine("using namespace rapidjson;");

	return;
}

void DataWappereGenerator::FileStaticVar()
{
	if(!m_bIsMsg)
	{
		return;
	}

	sprintf(m_charArrTmp, "static Document *g_%sDoc = nullptr;\n"
						  "static SchemaDocument *g_%sSmDoc = nullptr;\n"
						  "static mutex g_%sMutex;",
			m_msg.name.c_str(),
			m_msg.name.c_str(),
			m_msg.name.c_str());

	WriteWithNewLine(m_charArrTmp);
}

void DataWappereGenerator::ClassStart()
{
	string name(m_msg.name);
	ToUpperCase(name[0]);

	sprintf(m_charArrTmp, "class C%s : public CViidBaseData\n{", name.c_str());
	WriteWithNewLine(m_charArrTmp);
	++m_nIdent;
}

void DataWappereGenerator::ClassEnd()
{
	--m_nIdent;
	Write("};");

	return;
}

void DataWappereGenerator::TypeDef()
{
	string name(m_msg.name);
	ToUpperCase(name[0]);

	sprintf(m_charArrTmp, "typedef shared_ptr<C%s> sharedPtr;", name.c_str());
	WriteWithNewLine(m_charArrTmp);
}

void DataWappereGenerator::create()
{
	string name(m_msg.name);
	ToUpperCase(name[0]);
	sprintf(m_charArrTmp, "static sharedPtr Create%s()\n{",name.c_str());
	WriteWithNewLine(m_charArrTmp);
	++m_nIdent;

	sprintf(m_charArrTmp, "sharedPtr sp(new C%s);\n",
			name.c_str());
	WriteWithNewLine(m_charArrTmp);
	WriteWithNewLine("return sp;\n");

	--m_nIdent;
	WriteWithNewLine("}");
}

void DataWappereGenerator::createWithData()
{
	string name(m_msg.name);
	ToUpperCase(name[0]);
	sprintf(m_charArrTmp, "static sharedPtr Create%sWithData(%s *data)\n{",name.c_str(), m_msg.name.c_str());
	WriteWithNewLine(m_charArrTmp);
	++m_nIdent;

	sprintf(m_charArrTmp, "sharedPtr sp(new C%s(data));\n",name.c_str());
	WriteWithNewLine(m_charArrTmp);

	// in case of msg has no entryTime
	if(m_msg.bHasEntryTime)
	{
		WriteWithNewLine("sp->m_data->set_entrytime(time(nullptr));");
	}

	WriteWithNewLine("return sp;\n");
	--m_nIdent;
	WriteWithNewLine("}");
}

void DataWappereGenerator::construct()
{
	string name(m_msg.name);
	ToUpperCase(name[0]);

	// constructor witout parameter
	sprintf(m_charArrTmp, "C%s()\n", name.c_str());
	Write(m_charArrTmp);

	WriteWithNewLine();

	WriteWithNewLine("{\n");
	++m_nIdent;

	sprintf(m_charArrTmp, "m_data = new %s;\n"
						  "m_bOutData = false;\n",
			m_msg.name.c_str());
	WriteWithNewLine(m_charArrTmp);
	if(m_bIsMsg)
	{
		WriteWithNewLine("InitSchema();");
	}

	if(m_msg.name == "ImageListObject")
	{
		WriteWithNewLine("SetType(CT_IM_NO_OUT);");
	}
	else if(m_msg.name == "VideoSliceListObject")
	{
		WriteWithNewLine("SetType(CT_VS_NO_OUT);");
	}
	else if(m_msg.name == "ImageListMsg")
	{
		WriteWithNewLine("SetType(CT_INV);");
	}
	else if(m_msg.name == "VideoSliceListMsg")
	{
		WriteWithNewLine("SetType(CT_INV);");
	}

	--m_nIdent;
	WriteWithNewLine("}\n");

	// constructor with parameter of 'm_data'
	sprintf(m_charArrTmp, "C%s(%s *data)\n{",name.c_str(), m_msg.name.c_str());
	WriteWithNewLine(m_charArrTmp);
	++m_nIdent;

	WriteWithNewLine("m_data = data;\n"
					 "m_bOutData = true;\n");

	if(m_bIsMsg)
	{
		WriteWithNewLine("InitSchema();");
	}

	if(m_msg.name == "ImageListObject")
	{
		WriteWithNewLine("SetType(CT_IM_NO_OUT);");
	}
	else if(m_msg.name == "VideoSliceListObject")
	{
		WriteWithNewLine("SetType(CT_VS_NO_OUT);");
	}
	else if(m_msg.name == "ImageListMsg")
	{
		WriteWithNewLine("SetType(CT_INV);");
	}
	else if(m_msg.name == "VideoSliceListMsg")
	{
		WriteWithNewLine("SetType(CT_INV);");
	}

	--m_nIdent;
	WriteWithNewLine("}\n");
}

void DataWappereGenerator::destruct()
{
	string name(m_msg.name);
	ToUpperCase(name[0]);

	sprintf(m_charArrTmp, "~C%s()", name.c_str());
	WriteWithNewLine(m_charArrTmp);
	WriteWithNewLine("{");

	++m_nIdent;

	WriteWithNewLine("Release();");

	--m_nIdent;

	WriteWithNewLine("}");

}

void DataWappereGenerator::InitSchema()
{
	WriteWithNewLine("void InitSchema()\n{");
	++m_nIdent;

	if(!m_bIsMsg)
	{
		WriteWithNewLine("return;");
	}
	else
	{


		sprintf(m_charArrTmp,
							"if(g_%sSmDoc)\n"
							"{\n"
							"\treturn;\n"
							"}\n"
							"g_%sMutex.lock();\n"
							"if(!g_%sSmDoc)\n{\n"
							"\tg_%sDoc = new Document;\n"
							"\tg_%sDoc->Parse(g_str%sSchema);\n"
							"\tg_%sSmDoc = new SchemaDocument(*g_%sDoc);\n"
							"}\n"
							"g_%sMutex.unlock();\n",
				m_msg.name.c_str(),
				m_msg.name.c_str(),
				m_msg.name.c_str(),
				m_msg.name.c_str(),
				m_msg.name.c_str(),
				m_msg.name.c_str(),
				m_msg.name.c_str(),
				m_msg.name.c_str(),
				m_msg.name.c_str());

		WriteWithNewLine(m_charArrTmp);
	}

	--m_nIdent;
	WriteWithNewLine("}");
}

void DataWappereGenerator::Release()
{
	WriteWithNewLine("void Release()\n{");
	++m_nIdent;

	WriteWithNewLine("if(m_data && !m_bOutData)\n"
					 "{\n"
					 "\tdelete m_data;\n"
					 "\tm_data = nullptr;\n"
					 "}");

	--m_nIdent;
	WriteWithNewLine("}");
}

void DataWappereGenerator::ToCdb()
{
	CCdb sql(m_sqlFileName);
	sql.scan();

	WriteWithNewLine("// experimental");
	sprintf(m_charArrTmp, "static void ProtoToCdb(cdb::RowMutation::Builder *row_mutation_build, const %s *prot)\n{",
			m_msg.name.c_str());

	WriteWithNewLine(m_charArrTmp);
	++m_nIdent;

	const JsonKey *pJsonKey = nullptr;
	if(!m_msg.m_vecFields.empty())
	{
		for(const auto & cdbkey : sql.record.Keys)
		{
			if(cdbkey.isPrimary)
			{
				continue;
			}

			pJsonKey = GetJsonKeyWithName(cdbkey.name);
			if(!pJsonKey)
			{
				g_logger->warn("'{}' in [{}] not found in [{}.proto]", cdbkey.name, m_sqlFileName, m_msg.fileName);
//				sprintf(m_charArrTmp, "// %s not found in proto\n", cdbkey.name.c_str());
//				WriteWithNewLine(m_charArrTmp);
				continue;
			}

			if(cdbkey.type == "string")
			{
				if(pJsonKey->type == "string")
				{
					sprintf(m_charArrTmp, "row_mutation_build->SetString(\"%s\", prot->%s());",cdbkey.name.c_str(), pJsonKey->fget.c_str());
				}
				else
				{
					// int
					sprintf(m_charArrTmp, "row_mutation_build->SetString(\"%s\", IntTOString(prot->%s()));",cdbkey.name.c_str(), pJsonKey->fget.c_str());
				}
			}
			else if(cdbkey.type == "integer" || cdbkey.type == "long")
			{
				if(pJsonKey->type == "int64")
				{
					sprintf(m_charArrTmp, "row_mutation_build->SetInt64(\"%s\", prot->%s());",cdbkey.name.c_str(), pJsonKey->fget.c_str());
				}
				else
				{
					// string
					sprintf(m_charArrTmp, "row_mutation_build->SetInt64(\"%s\", stringToInt(prot->%s()));",cdbkey.name.c_str(), pJsonKey->fget.c_str());
				}

			}
			else if(cdbkey.type == "double")
			{
				sprintf(m_charArrTmp, "row_mutation_build->SetDouble(\"%s\", prot->%s());",cdbkey.name.c_str(), pJsonKey->fget.c_str());
			}
			else if(cdbkey.type == "bool")
			{
				sprintf(m_charArrTmp, "row_mutation_build->SetInt64(\"%s\", prot->%s());",cdbkey.name.c_str(), pJsonKey->fget.c_str());
			}
			else if(cdbkey.type == "timestamp" && pJsonKey->type == "int64")
			{
				sprintf(m_charArrTmp, "row_mutation_build->SetTimestamp(\"%s\", UnixTimeToTimeVal(prot->%s()));",cdbkey.name.c_str(), pJsonKey->fget.c_str());
			}
			else
			{
				g_logger->error("unkonwn type,cdb: {} in {} at {}, proto: {} in {}\n",
								cdbkey.type, cdbkey.name, m_sqlFileName, pJsonKey->type, pJsonKey->name);
			}

			WriteWithNewLine(m_charArrTmp);
		}


//		for(const auto & key : m_msg.m_vecFields)
//		{
//			if(key.name == "FaceID" ||
//			   key.name == "MotorVehicleID")
//			{
//				// key in cdb
//				continue;
//			}

//			// kdface not write
//			if(m_msg.fileName == "kdface")
//			{
//				if(key.name == "EntryTime" ||
//						key.name == "TabID")
//				{
//					continue;
//				}
//			}

//			if(key.type == "string")
//			{
//				sprintf(m_charArrTmp, "row_mutation_build->SetString(\"%s\", prot->%s());",key.name.c_str(), key.fget.c_str());
//			}
//			else if(key.type == "int64")
//			{
//				if(key.isTime)
//				{
//					sprintf(m_charArrTmp, "row_mutation_build->SetTimestamp(\"%s\", UnixTimeToTimeVal(prot->%s()));",key.name.c_str(), key.fget.c_str());
//				}
//				else
//				{
//					sprintf(m_charArrTmp, "row_mutation_build->SetInt64(\"%s\", prot->%s());",key.name.c_str(), key.fget.c_str());
//				}
//			}
//			else if(key.type == "double")
//			{
//				sprintf(m_charArrTmp, "row_mutation_build->SetDouble(\"%s\", prot->%s());",key.name.c_str(), key.fget.c_str());
//			}
//			else if(key.type == "bool")
//			{
//				sprintf(m_charArrTmp, "row_mutation_build->SetInt64(\"%s\", prot->%s());",key.name.c_str(), key.fget.c_str());
//			}
//			else
//			{
//				g_logger->error("unkonwn type : %s\n", key.type.c_str());
//			}

//			WriteWithNewLine(m_charArrTmp);
//		}
	}

	--m_nIdent;
	WriteWithNewLine("}");
}

void DataWappereGenerator::ToString()
{
	WriteWithNewLine("string &ToString(string &str, bool read = false)\n"
					 "{");
	++m_nIdent;

	WriteWithNewLine("rapidjson::StringBuffer buffer;\n"
					 "rapidjson::Writer<StringBuffer> writer(buffer);\n");

	WriteWithNewLine("ToStringWriter(writer, read);");


	WriteWithNewLine("str = buffer.GetString();\nreturn str;");

	--m_nIdent;
	WriteWithNewLine("}");
}

void DataWappereGenerator::ToStringWriter()
{
	WriteWithNewLine("void ToStringWriter(rapidjson::Writer<StringBuffer> &writer, bool read = false)\n"
					 "{");
	++m_nIdent;

	WriteWithNewLine("writer.StartObject();");
	WriteWithNewLine();

	// � €鍗� 被鍨嬶紝� €鍗� 被鍨嬩笉鏄痑rray
	if(!m_msg.m_vecFields.empty())
	{

		for(const auto & key : m_msg.m_vecFields)
		{
			// subimageinfo special handle
			if(m_msg.name == "SubImageInfo_Proto")
			{
				if(	key.name == "DeviceType" ||
					key.name == "DeviceSNNo" ||
					key.name == "ImeiSn" ||
					key.name == "APSId" ||
					key.name  == "SelfDefData" ||
					key.name == "DataSize")
				{
					continue;
				}
			}


			if(key.name == "LocalPath")
			{
				continue;
			}

			if(key.name == "MountPath")
			{
				WriteWithNewLine("if(!read)\n"
								 "{\n"
								 "\twriter.String(\"MountPath\");\n"
								 "\twriter.String(m_data->mountpath().c_str());\n"
								 "}");
				continue;
			}

			// GeoPoint
			if(key.isGeoPoint)
			{
				continue;
			}

			if(m_msg.name == "DispositionNotificationListMsg")
			{
				if(key.name == "ReceiveAddr")
				{
					continue;
				}
			}

			if(key.name == "TabID")
			{
				continue;
			}

			// data in image will be move to subimage
			if(m_msg.name == "SubImageInfo_Proto")
			{
				if(key.name == "Data")
				{
					WriteWithNewLine("if(read)\n"
									 "{\n"
									 "\twriter.String(\"Data\");\n"
									 "\twriter.String(m_data->data().c_str());\n"
									 "}");
					continue;

				}
			}

			// key
			if(key.name == "Orientation" && m_msg.name == "GPSData_Proto")
			{
				WriteWithNewLine("if(read)\n"
								 "{\n"
								 "\twriter.String(\"Direction\");\n"
								 "}\n"
								 "else\n"
								 "{\n"
								 "\twriter.String(\"Orientation\");\n"
								 "}");
			}
			else
			{
				sprintf(m_charArrTmp, "writer.String(\"%s\");", key.name.c_str());
				WriteWithNewLine(m_charArrTmp);
			}

			// value
			if(key.type == "string")
			{
				sprintf(m_charArrTmp, "writer.String(m_data->%s().c_str());", key.fget.c_str());
				if(key.stringCanBeInt)
				{
					sprintf(m_charArrTmp, "writer.Int64(stringToInt(m_data->%s()));", key.fget.c_str());
				}
				else
				{
					sprintf(m_charArrTmp, "writer.String(m_data->%s().c_str());", key.fget.c_str());
				}
			}
			else if(key.type == "int64")
			{
				if(key.isEntryTime)
				{
					// 淇濇寔涓€鑷
					sprintf(m_charArrTmp, "if(read)\n"
										  "{\n"
										  "\twriter.String(%s(getEntryTime()).c_str());\n"
										  "}\n"
										  "else\n"
										  "{\n"
										  "\twriter.String(UnixTimeToPrettyTime(getEntryTime()).c_str());\n"
										  "}",
							"UnixTimeToRawTime");
				}
				else if(key.isTime)
				{
					sprintf(m_charArrTmp,"if(read)\n"
										 "{\n"
										 "\twriter.String(UnixTimeToRawTime(m_data->%s()).c_str());\n"
										 "}\n"
										 "else\n"
										 "{\n"
										 "\twriter.String(UnixTimeToPrettyTime(m_data->%s()).c_str());\n"
										 "}",
							key.fget.c_str(),
							key.fget.c_str());
				}
				else
				{
					sprintf(m_charArrTmp, "writer.Int64(m_data->%s());", key.fget.c_str());
				}
			}
			else if(key.type == "double")
			{
				sprintf(m_charArrTmp, "writer.Double(m_data->%s());", key.fget.c_str());
			}
			else if(key.type == "bool")
			{
				sprintf(m_charArrTmp, "writer.Bool(m_data->%s());", key.fget.c_str());
			}
			else
			{
				g_logger->error("unkonwn type : %s\n", key.type.c_str());
			}

			WriteWithNewLine(m_charArrTmp);
			WriteWithNewLine();
		}
	}

	// GeoPoint
	if(!m_msg.GeoPoint.lat.name.empty())
	{
		sprintf(m_charArrTmp,
				"if(!read)\n"
				"{\n"
				"\twriter.String(\"%s\");\n"
				"\twriter.StartObject();\n"
				"\twriter.String(\"lon\");\n"
				"\twriter.Double(m_data->%s());\n"
				"\twriter.String(\"lat\");\n"
				"\twriter.Double(m_data->%s());\n"
				"\twriter.EndObject();\n"
				"}\n"
				"else\n"
				"{\n"
				"\twriter.String(\"%s\");\n"
				"\twriter.Double(m_data->%s());\n"
				"\t\n"
				"\twriter.String(\"%s\");\n"
				"\twriter.Double(m_data->%s());\n"
				"}",
				m_msg.GeoPoint.name.c_str(),
				m_msg.GeoPoint.lon.fget.c_str(),
				m_msg.GeoPoint.lat.fget.c_str(),
				m_msg.GeoPoint.lon.name.c_str(),
				m_msg.GeoPoint.lon.fget.c_str(),
				m_msg.GeoPoint.lat.name.c_str(),
				m_msg.GeoPoint.lat.fget.c_str());
		WriteWithNewLine(m_charArrTmp);
	}

	// 澶嶅悎绫诲瀷
	if(!m_msg.m_VecSubMsg.empty())
	{
		for(const auto &msg : m_msg.m_VecSubMsg)
		{

			// special handle for subimagelist
			if(msg.fieldName == "SubImageList")
			{
				WriteWithNewLine("if(m_data->subimagelist_size())\n"
								 "{\n"
								 "\n"
								 "\tif(read)\n"
								 "\t{\n"
								 "\t\twriter.String(\"SubImageList\");\n"
								 "\t\twriter.StartObject();\n"
								 "\t\twriter.String(\"SubImageInfoObject\");\n"
								 "\t\twriter.StartArray();\n"
								 "\t\tfor(auto & RawP : *(m_data->mutable_subimagelist()))\n"
								 "\t\t{\n"
								 "\t\t\tauto sp = CSubImageInfo_Proto::CreateSubImageInfo_ProtoWithData(&RawP);\n"
								 "\t\t\tsp->setEntryTime(getEntryTime());\n"
								 "\t\t\tsp->setExpiredTime(getExpiredTime());\n"
								 "\t\t\tsp->ToStringWriter(writer, read);\n"
								 "\t\t}\n"
								 "\t\twriter.EndArray();\n"
								 "\t\twriter.EndObject();\n"
								 "\t}\n"
								 "\telse\n"
								 "\t{\n"
								 "\t\twriter.String(\"SubImageList\");\n"
								 "\t\twriter.StartArray();\n"
								 "\t\tfor(auto & RawP : *(m_data->mutable_subimagelist()))\n"
								 "\t\t{\n"
								 "\t\t\tauto sp = CSubImageInfo_Proto::CreateSubImageInfo_ProtoWithData(&RawP);\n"
								 "\t\t\tsp->setEntryTime(getEntryTime());\n"
								 "\t\t\tsp->setExpiredTime(getExpiredTime());\n"
								 "\t\t\tsp->ToStringWriter(writer, read);\n"
								 "\t\t}\n"
								 "\t\twriter.EndArray();\n"
								 "\t}\n"
								 "}");

				WriteWithNewLine();
				continue;
			}

			if(msg.fieldName == "FeatureList")
			{
				WriteWithNewLine("if(m_data->featurelist_size())\n"
								 "{\n"
								 "\n"
								 "\tif(read)\n"
								 "\t{\n"
								 "\t\twriter.String(\"FeatureList\");\n"
								 "\t\twriter.StartObject();\n"
								 "\t\twriter.String(\"FeatureObject\");\n"
								 "\t\twriter.StartArray();\n"
								 "\t\tfor(auto & RawP : *(m_data->mutable_featurelist()))\n"
								 "\t\t{\n"
								 "\t\t\tauto sp = CFeature_Proto::CreateFeature_ProtoWithData(&RawP);\n"
								 "\t\t\tsp->setEntryTime(getEntryTime());\n"
								 "\t\t\tsp->setExpiredTime(getExpiredTime());\n"
								 "\t\t\tsp->ToStringWriter(writer, read);\n"
								 "\t\t}\n"
								 "\t\twriter.EndArray();\n"
								 "\t\twriter.EndObject();\n"
								 "\t}\n"
								 "\telse\n"
								 "\t{\n"
								 "\t\twriter.String(\"FeatureList\");\n"
								 "\t\twriter.StartArray();\n"
								 "\t\tfor(auto & RawP : *(m_data->mutable_featurelist()))\n"
								 "\t\t{\n"
								 "\t\t\tauto sp = CFeature_Proto::CreateFeature_ProtoWithData(&RawP);\n"
								 "\t\t\tsp->setEntryTime(getEntryTime());\n"
								 "\t\t\tsp->setExpiredTime(getExpiredTime());\n"
								 "\t\t\tsp->ToStringWriter(writer, read);\n"
								 "\t\t}\n"
								 "\t\twriter.EndArray();\n"
								 "\t}\n"
								 "}");

				WriteWithNewLine();
				continue;
			}

			// gpsdata save alone
			if(msg.fieldName == "GPSData")
			{
				if(msg.isArrray)
				{
					sprintf(m_charArrTmp,
							"if(m_data->%s() && read)\n"
							"{\n"
							"\n"
							"\twriter.String(\"%s\");\n"
							"\twriter.StartArray();\n"
							"\tfor(auto & RawP : *(m_data->mutable_%s()))\n"
							"\t{\n"
							"\t\tauto sp = C%s::Create%sWithData(&RawP);\n"
							"\t\tsp->setEntryTime(getEntryTime());\n"
							"\t\tsp->setExpiredTime(getExpiredTime());\n"
							"\t\tsp->ToStringWriter(writer, read);\n"
							"\t}\n"
							"\twriter.EndArray();\n"
							"}",
							msg.fsize.c_str(),
							msg.fieldName.c_str(),
							msg.fget.c_str(),
							msg.name.c_str(),
							msg.name.c_str());
				}
				else
				{
					sprintf(m_charArrTmp,
							"if(m_data->has_%s() && read)\n{\n"
							"\tauto p = m_data->%s();\n"
							"\tauto sp = C%s::Create%sWithData(&p);\n"
							"\tsp->setEntryTime(getEntryTime());\n"
							"\tsp->setExpiredTime(getExpiredTime());\n"
							"\twriter.String(\"%s\");\n"
							"\tsp->ToStringWriter(writer, read);\n}\n",
							msg.fget.c_str(),
							msg.fget.c_str(),
							msg.name.c_str(),
							msg.name.c_str(),
							msg.fieldName.c_str());
				}

				WriteWithNewLine(m_charArrTmp);

				WriteWithNewLine();
				continue;
			}

			if(msg.isArrray)
			{
				sprintf(m_charArrTmp,
						"if(m_data->%s())\n"
						"{\n"
						"\n"
						"\twriter.String(\"%s\");\n"
						"\twriter.StartArray();\n"
						"\tfor(auto & RawP : *(m_data->mutable_%s()))\n"
						"\t{\n"
						"\t\tauto sp = C%s::Create%sWithData(&RawP);\n"
						"\t\tsp->setEntryTime(getEntryTime());\n"
						"\t\tsp->setExpiredTime(getExpiredTime());\n"
						"\t\tsp->ToStringWriter(writer, read);\n"
						"\t}\n"
						"\twriter.EndArray();\n"
						"}",
						msg.fsize.c_str(),
						msg.fieldName.c_str(),
						msg.fget.c_str(),
						msg.name.c_str(),
						msg.name.c_str());
			}
			else
			{
				sprintf(m_charArrTmp,
						"if(m_data->has_%s())\n{\n"
						"\tauto p = m_data->%s();\n"
						"\tauto sp = C%s::Create%sWithData(&p);\n"
						"\tsp->setEntryTime(getEntryTime());\n"
						"\tsp->setExpiredTime(getExpiredTime());\n"
						"\twriter.String(\"%s\");\n"
						"\tsp->ToStringWriter(writer, read);\n}\n",
						msg.fget.c_str(),
						msg.fget.c_str(),
						msg.name.c_str(),
						msg.name.c_str(),
						msg.fieldName.c_str());
			}

			WriteWithNewLine(m_charArrTmp);

			WriteWithNewLine();
		}
	}

	if(m_msg.name != "SubImageInfo_Proto" &&
			m_msg.name != "Feature_Proto" &&
			(!m_msg.bHasEntryTime || !m_msg.bHasExpireDate))
	{
		WriteWithNewLine("if(!read)\n{");
		++m_nIdent;

		// entryTime
		if(!m_msg.bHasEntryTime)
		{
			WriteWithNewLine("writer.String(\"EntryTime\");\n"
							 "writer.String(UnixTimeToPrettyTime(getEntryTime()).c_str());");
		}

		// expiredTime
		if(!m_msg.bHasExpireDate)
		{
			WriteWithNewLine("writer.String(\"KDExpiredDate\");\n"
							 "writer.String(UnixTimeToPrettyTime(getExpiredTime()).c_str());");
		}

		--m_nIdent;
		WriteWithNewLine("}");
	}

	WriteWithNewLine();

	WriteWithNewLine("writer.EndObject();");

	--m_nIdent;
	WriteWithNewLine("}");
}

void DataWappereGenerator::ToStringByProto()
{
	WriteWithNewLine("string& ToStringByProto(string &str) const\n"
					 "{");

	++m_nIdent;

	WriteWithNewLine("google::protobuf::util::JsonPrintOptions op;\n"
					 "op.add_whitespace = false;\n"
					 "\n"
					 "google::protobuf::util::Status st = MessageToJsonString(*m_data, &str, op);\n"
					 "if(!st.ok())\n"
					 "{\n"
					 "\tstr.clear();\n"
					 "}\n"
					 "\n"
					 "return str;");

	--m_nIdent;

	WriteWithNewLine("}");

	return;
}

void DataWappereGenerator::ToStringWithSpecifiedField()
{
	WriteWithNewLine("string &ToStringWithSpecifiedField(string &str, const set<string> fields)\n"
					 "{");
	++m_nIdent;

	WriteWithNewLine("rapidjson::StringBuffer buffer;\n"
					 "rapidjson::Writer<StringBuffer> writer(buffer);\n");
	WriteWithNewLine();

	WriteWithNewLine("writer.StartObject();");
	WriteWithNewLine();

	WriteWithNewLine("__attribute__((unused)) auto end = fields.end();");

	// 搴旇涓嶄細鎸囧畾澶嶅埗绫诲瀷
	if(!m_msg.m_vecFields.empty())
	{
		for(const auto & key : m_msg.m_vecFields)
		{
			sprintf(m_charArrTmp, "if(fields.find(\"%s\") != end)\n"
								  "{",
								  key.name.c_str());
			WriteWithNewLine(m_charArrTmp);
			++m_nIdent;

			if(key.name == "Orientation" && m_msg.name == "GPSData_Proto")
			{
				sprintf(m_charArrTmp, "writer.String(\"%s\");", "Direction");
			}
			else
			{
				sprintf(m_charArrTmp, "writer.String(\"%s\");", key.name.c_str());
			}
			WriteWithNewLine(m_charArrTmp);

			if(key.type == "string")
			{
				sprintf(m_charArrTmp, "writer.String(m_data->%s().c_str());", key.fget.c_str());
				sprintf(m_charArrTmp, "writer.String(m_data->%s().c_str());", key.fget.c_str());
			}
			else if(key.type == "int64")
			{
//				string t = "Time";
//				bool isTime = false;
//				bool isEntryTime = false;
//				if(key.name.length() > t.length())
//				{
//					isTime = (key.name.compare(key.name.length()-t.length(), t.length(), t) == 0);
//					isEntryTime = (key.name == "EntryTime");
//				}

				if(key.isEntryTime)
				{
					// 淇濇寔涓€鑷
					sprintf(m_charArrTmp, "writer.String(%s(getEntryTime()).c_str());\n",
							"UnixTimeToRawTime");
				}
				else if(key.isTime)
				{
					sprintf(m_charArrTmp,"writer.String(UnixTimeToRawTime(m_data->%s()).c_str());\n",
							key.fget.c_str());
				}
				else
				{
					sprintf(m_charArrTmp, "writer.Int64(m_data->%s());", key.fget.c_str());
				}
			}
			else if(key.type == "double")
			{
				sprintf(m_charArrTmp, "writer.Double(m_data->%s());", key.fget.c_str());
			}
			else if(key.type == "bool")
			{
				sprintf(m_charArrTmp, "writer.Bool(m_data->%s());", key.fget.c_str());
			}
			else
			{
				g_logger->error("unkonwn type : %s\n", key.type.c_str());
			}

			WriteWithNewLine(m_charArrTmp);

			--m_nIdent;
			WriteWithNewLine("}");
			WriteWithNewLine();
		}
	}

	// 澶嶅悎绫诲瀷
	if(!m_msg.m_VecSubMsg.empty())
	{
		for(const auto &msg : m_msg.m_VecSubMsg)
		{
			if(msg.fieldName == "SubImageList")
			{
				// TODO complete this
				continue;
			}

			if(msg.fieldName == "FeatureList")
			{
				// TODO complete this
				continue;
			}

			WriteWithNewLine("{");
			++m_nIdent;

			if(msg.isArrray)
			{
				sprintf(m_charArrTmp,
						"int cnt = m_data->%s();\n"
						"writer.String(\"%s\");\n"
						"writer.StartArray();\n"
						"for (int i=0; i<cnt; ++i)\n"
						"{\n"
						"\tauto RawP = m_data->%s(i);\n"
						"\tauto sp = C%s::Create%sWithData(&RawP);\n"
						"\tsp->setEntryTime(getEntryTime());\n"
						"\tsp->setExpiredTime(getExpiredTime());\n"
						"\tsp->ToStringWriter(writer, true);\n"
						"}\n"
						"writer.EndArray();",
						msg.fsize.c_str(),
						msg.fieldName.c_str(),
						msg.fget.c_str(),
						msg.name.c_str(),
						msg.name.c_str());
			}
			else
			{
				sprintf(m_charArrTmp,
						"auto p = m_data->%s();\n"
						"auto sp = C%s::Create%sWithData(&p);\n"
						"sp->setEntryTime(getEntryTime());\n"
						"sp->setExpiredTime(getExpiredTime());\n"
						"writer.String(\"%s\");\n"
						"sp->ToStringWriter(writer, true);\n",
						msg.fget.c_str(),
						msg.name.c_str(),
						msg.name.c_str(),
						msg.fieldName.c_str());
			}

			WriteWithNewLine(m_charArrTmp);
			--m_nIdent;
			WriteWithNewLine("}");

			WriteWithNewLine();
		}
	}

	WriteWithNewLine("writer.EndObject();");

	WriteWithNewLine("str = buffer.GetString();\nreturn str;");
	--m_nIdent;
	WriteWithNewLine("}");
}

void DataWappereGenerator::Serialize()
{
	WriteWithNewLine("bool Serialize(CSerialBuf &buf) const\n"
					 "{");

	++m_nIdent;

	WriteWithNewLine("buf.SetLen(m_data->ByteSize());");

	WriteWithNewLine("return m_data->SerializeToArray(buf.GetBuf(), buf.GetLen());");

	--m_nIdent;

	WriteWithNewLine("}");

	return;
}

void DataWappereGenerator::DeSerial()
{
	WriteWithNewLine("bool DeSerialize(const void * data, int size)\n"
					 "{");

	++m_nIdent;

	WriteWithNewLine("return m_data->ParseFromArray(data, size);");

	--m_nIdent;

	WriteWithNewLine("}");

	return;
}

void DataWappereGenerator::FromString()
{
	WriteWithNewLine("bool FromString(const string &str, bool validate = true)\n"
					 "{");
	++m_nIdent;

	if(m_bIsMsg)
	{
//		sprintf(m_charArrTmp,
//				"auto p = new C%s(this->m_data);\n"
//				"viidJsonReadHandler handler(p);\n"
//				"Reader rd;\n"
//				"StringStream ss(str.c_str());\n",
//				m_msg.name.c_str());

//		WriteWithNewLine(m_charArrTmp);

		WriteWithNewLine("viidJsonReadHandler handler(this);\n"
						 "Reader rd;\n"
						 "StringStream ss(str.c_str());\n");

		WriteWithNewLine();

		sprintf(m_charArrTmp,
				"if(likely(validate))\n"
				"{\n"
				"\tGenericSchemaValidator<SchemaDocument, viidJsonReadHandler> validator(*(g_%sSmDoc), handler);\n"
				"\tParseResult ok = rd.Parse<kParseValidateEncodingFlag>(ss, validator);\n"
				"\tif(!validator.IsValid())\n"
				"\t{\n"
				"\t\tStringBuffer sb;\n"
				"\t\tWriter<StringBuffer> w(sb);\n"
				"\t\tvalidator.GetError().Accept(w);\n"
				"\t\tSetErrStr(sb.GetString());\n"
				"\t\treturn false;\n"
				"\t}\n"
				"\telse if(!ok)\n"
				"\t{\n"
				"\t\tstring err(GetParseError_En(ok.Code()));\n"
				"\t\tSetErrStr(err);\n"
				"\t\treturn false;\n"
				"\t}\n"
				"}\n"
				"else\n"
				"{\n"
				"\tParseResult ok = rd.Parse(ss, handler);\n"
				"\tif(!ok)\n"
				"\t{\n"
				"\t\tstring err(GetParseError_En(ok.Code()));\n"
				"\t\tSetErrStr(err);\n"
				"\t\treturn false;\n"
				"\t}\n"
				"}\n",
				m_msg.name.c_str());

		WriteWithNewLine(m_charArrTmp);

		// EntryTime
		if(m_msg.bHasEntryTime)
		{
			WriteWithNewLine("m_data->set_entrytime(time(nullptr));");
		}
	}

	WriteWithNewLine("return true;");

	--m_nIdent;
	WriteWithNewLine("}");
}

void DataWappereGenerator::FromStringNoCheck()
{
	WriteWithNewLine("bool FromStringNoCheck(const string &str)\n"
					 "{");
	++m_nIdent;

	sprintf(m_charArrTmp, "auto sp = C%s::Create%sWithData(this->m_data);\n"
						  "viidJsonReadHandler handler(sp);\n"
						  "Reader rd;\n"
						  "StringStream ss(str.c_str());\n"
						  "if(!rd.Parse<kParseValidateEncodingFlag>(ss, handler))\n"
						  "{\n"
						  "\treturn  false;\n"
						  "}\n"
						  "return true;",
			m_msg.name.c_str(),
			m_msg.name.c_str());

	WriteWithNewLine(m_charArrTmp);

	--m_nIdent;
	WriteWithNewLine("}");
}

void DataWappereGenerator::FromStringProto()
{
	WriteWithNewLine("bool FromStringProto(const string &str)\n"
					 "{");
	++m_nIdent;

	WriteWithNewLine("google::protobuf::util::JsonParseOptions op;\n"
					 "op.ignore_unknown_fields = true;\n"
					 "JsonStringToMessage(str, this->m_data, op);\n"
					 "return true;");

	--m_nIdent;
	WriteWithNewLine("}");
}

void DataWappereGenerator::getSet()
{
	// data
	sprintf(m_charArrTmp, "%s *GetData()\n"
						  "{\n"
						  "\treturn  m_data;\n"
						  "}",
			m_msg.name.c_str());

	WriteWithNewLine(m_charArrTmp);

	WriteWithNewLine();

	/*
	// � €鍗� 被鍨
	if(!m_msg.m_mapFields.empty())
	{
		for(const auto kv : m_msg.m_mapFields)
		{
			auto field = kv.second;
			string name = field.name;
			string type = field.type;
			if(type == "int64")
			{
				type = "int64_t";
			}

			ToUpperCase(name[0]);

			sprintf(m_charArrTmp, "void Set%s(const %s src)\n"
								  "{\n"
								  "\tm_data->%s(src);\n"
								  "}",
					name.c_str(),
					type.c_str(),
					field.fset.c_str());

			WriteWithNewLine(m_charArrTmp);

			sprintf(m_charArrTmp, "%s Get%s() const\n"
								  "{\n"
								  "\t return m_data->%s();\n"
								  "}",
					type.c_str(),
					name.c_str(),
					field.fget.c_str());

			WriteWithNewLine(m_charArrTmp);
			WriteWithNewLine();
		}
	}

	// 澶嶆潅绫诲瀷锛宻ize锛get锛set
	if(!m_msg.m_VecSubMsg.empty())
	{
		for(const auto msg : m_msg.m_VecSubMsg)
		{
			sprintf(m_charArrTmp, "%s *Add%s()\n"
								  "{\n"
								  "\treturn  m_data->%s();\n"
								  "}",
					msg.name.c_str(),
					msg.name.c_str(),
					msg.fadder.c_str());

			WriteWithNewLine(m_charArrTmp);

			if(msg.isArrray)
			{
				string getSize(msg.fget);
				getSize.append("_size");

				sprintf(m_charArrTmp, "int Get%sObjectSize()\n"
									  "{\n"
									  "\treturn m_data->%s();\n"
									  "}",
						msg.name.c_str(),
						getSize.c_str());
				WriteWithNewLine(m_charArrTmp);

				sprintf(m_charArrTmp, "%s Get%s(int index)\n"
									  "{\n"
									  "\treturn m_data->%s(index);\n"
									  "}",
						msg.name.c_str(),
						msg.name.c_str(),
						msg.fget.c_str());
				WriteWithNewLine(m_charArrTmp);
			}
			else
			{
				sprintf(m_charArrTmp, "const %s& Get%s()\n"
									  "{\n"
									  "\treturn m_data->%s();\n"
									  "}",
						msg.name.c_str(),
						msg.name.c_str(),
						msg.fget.c_str());
				WriteWithNewLine(m_charArrTmp);
			}
			WriteWithNewLine();
		}
	}
*/

	// EntryTime鐗规畩澶勭悊
	if(m_msg.bHasEntryTime)
	{
		// overload EntryTime set/get
		WriteWithNewLine("void setEntryTime(const time_t src) {m_data->set_entrytime(src);}\n"
						 "time_t getEntryTime() const {return m_data->entrytime();}");
	}
}

void DataWappereGenerator::ObjectBegin()
{
	WriteWithNewLine("bool ObjectBegin(hash_t hKey, CViidBaseData *&newPtr)\n{");
	++m_nIdent;

	if(!m_msg.m_VecSubMsg.empty())
	{
		WriteWithNewLine("switch (hKey)\n"
						 "{");

		for(const auto & msg : m_msg.m_VecSubMsg)
		{

			string className(msg.name);
			ToUpperCase(className[0]);

			string lowCaseMessageName(msg.name);
			ToLowCase(lowCaseMessageName);

			// featureList, subImageList special handle
			if(msg.fieldName == "FeatureList")
			{
				sprintf(m_charArrTmp,
						"case \"FeatureObject\"_hash:// %lu\n"
						"\t{\n"
						"\t\tauto p = m_data->add_featurelist();\n"
						"\t\tnewPtr = new CFeature_Proto(p);\n"
						"\t\tbreak;\n"
						"\t}",
						get_str_hash("FeatureObject"));

			}
			else if(msg.fieldName == "SubImageList")
			{
				sprintf(m_charArrTmp,
						"case \"SubImageInfoObject\"_hash:// %lu\n"
						"\t{\n"
						"\t\tauto p = m_data->add_subimagelist();\n"
						"\t\tnewPtr = new CSubImageInfo_Proto(p);\n"
						"\t\tbreak;\n"
						"\t}",
						get_str_hash("SubImageInfoObject"));

			}
			else
			{
				if(m_msg.name == "ImageListMsg" && msg.fieldName == "ImageList")
				{
					sprintf(m_charArrTmp,
							"case \"%s\"_hash:// %lu\n"
							"\t{\n"
							"\t\tSetType(CT_IM_NO_OBJECT);\n"
							"\t\tauto p = m_data->%s();\n"
							"\t\tnewPtr = new C%s(p);\n"
							"\t\tbreak;\n"
							"\t}",
							msg.fieldName.c_str(),
							get_str_hash(msg.fieldName.c_str()),
							msg.fadder.c_str(),
							msg.name.c_str());
				}
				else if(m_msg.name == "ImageListMsg" && msg.fieldName == "ImageListObject")
				{
					sprintf(m_charArrTmp,
							"case \"%s\"_hash:// %lu\n"
							"\t{\n"
							"\t\tSetType(CT_STD);\n"
							"\t\tauto p = m_data->%s();\n"
							"\t\tnewPtr = new C%s(p);\n"
							"\t\tbreak;\n"
							"\t}",
							msg.fieldName.c_str(),
							get_str_hash(msg.fieldName.c_str()),
							msg.fadder.c_str(),
							msg.name.c_str());
				}
				else if(m_msg.name == "VideoSliceListMsg" && msg.fieldName == "VideoSliceList")
				{
					sprintf(m_charArrTmp,
							"case \"%s\"_hash:// %lu\n"
							"\t{\n"
							"\t\tSetType(CT_VS_NO_OBJECT);\n"
							"\t\tauto p = m_data->%s();\n"
							"\t\tnewPtr = new C%s(p);\n"
							"\t\tbreak;\n"
							"\t}",
							msg.fieldName.c_str(),
							get_str_hash(msg.fieldName.c_str()),
							msg.fadder.c_str(),
							msg.name.c_str());
				}
				else if(m_msg.name == "VideoSliceListMsg" && msg.fieldName == "VideoSliceListObject")
				{
					sprintf(m_charArrTmp,
							"case \"%s\"_hash:// %lu\n"
							"\t{\n"
							"\t\tSetType(CT_STD);\n"
							"\t\tauto p = m_data->%s();\n"
							"\t\tnewPtr = new C%s(p);\n"
							"\t\tbreak;\n"
							"\t}",
							msg.fieldName.c_str(),
							get_str_hash(msg.fieldName.c_str()),
							msg.fadder.c_str(),
							msg.name.c_str());
				}
				else
				{
					sprintf(m_charArrTmp,
							"case \"%s\"_hash:// %lu\n"
							"\t{\n"
							"\t\tauto p = m_data->%s();\n"
							"\t\tnewPtr = new C%s(p);\n"
							"\t\tbreak;\n"
							"\t}",
							msg.fieldName.c_str(),
							get_str_hash(msg.fieldName.c_str()),
							msg.fadder.c_str(),
							msg.name.c_str());
				}
			}

			WriteWithNewLine(m_charArrTmp);
		}

		WriteWithNewLine("default:\n"
						 "\t{\n"
						 "\t\t// should not be here\n"
						 "\t\treturn false;\n"
						 "\t}");

		WriteWithNewLine("}");

		WriteWithNewLine("return true;");
	}
	else
	{
		WriteWithNewLine("// should not be here");
		WriteWithNewLine("return false;");
	}

	--m_nIdent;
	WriteWithNewLine("}");
}

void DataWappereGenerator::set(string fun, string type)
{
	fun.append("\n{");
	WriteWithNewLine(fun);
	++m_nIdent;

	bool hasType = false;
	for(const auto &key : m_msg.m_vecFields)
	{
		if(key.type == type)
		{
			hasType = true;
			break;
		}
	}

	if(hasType)
	{
		WriteWithNewLine("switch (hKey) \n{");

		for(const auto &field : m_msg.m_vecFields)
		{
			if(field.type == type)
			{
				// time is int but will given as string
				if(field.isTime)
				{
					continue;
				}

				CaseValue(field);
			}

			// double绫诲瀷鐨勬暟鎹紝鏈夋椂鍙兘浼氫互int褰� 紡缁欏嚭锛屽洜姝ゅ湪int閲屼篃鍐欎竴� 
			if(type == "int64")
			{
				if(field.type == "double")
				{
					CaseValue(field);
				}
			}

			// 鏈変簺瀛楁鏄� nt锛屼絾鏄湁鍙兘浼氫互string鐨勫舰寮忕粰鍑
			if(type == "string")
			{
				if((field.type == "int64") && (field.intCanBeStr || field.isTime))
				{
					CaseValue(field, true);
				}
			}
		}

		WriteWithNewLine("default:\n"
						 "\t{\n"
						 "\t\t// should not be here\n"
						 "\t\t// TODO log err\n"
						 "\t}");

		WriteWithNewLine("}");
	}

	WriteWithNewLine("return true;");

	--m_nIdent;
	WriteWithNewLine("}");
}

void DataWappereGenerator::CaseValue(const JsonKey &field, bool intBeStrinig)
{
	if(field.name == "Orientation" && m_msg.name == "GPSData_Proto")
	{
		sprintf(m_charArrTmp, "case \"%s\"_hash: // %lu","Direction", get_str_hash("Direction"));
	}
	else
	{
		sprintf(m_charArrTmp, "case \"%s\"_hash: // %lu",field.name.c_str(), get_str_hash(field.name.c_str()));
	}
	WriteWithNewLine(m_charArrTmp);

	++m_nIdent;
	WriteWithNewLine("{");
	++m_nIdent;

	if(intBeStrinig)	// 鐩� 鍙湁int鍨嬬殑锛屼細鏈夎繖绉嶆儏鍐
	{
		// time is int
		if(field.isEntryTime)
		{
			// EntryTime should set by viid
			// TODO break;
			// sprintf(m_charArrTmp, "m_data->%s(RawTimeToPretty(time(nullptr)));", field.fset.c_str());
//			WriteWithNewLine("if(unlikely(!CheckDateAfterSchema(value)))\n"
//							 "{\n"
//							 "\treturn false;\n"
//							 "}");
			sprintf(m_charArrTmp, "%s", "// viid generate");
		}
		else if(field.isTime)
		{
//			WriteWithNewLine("if(unlikely(!CheckDateAfterSchema(value)))\n"
//							 "{\n"
//							 "\treturn false;\n"
//							 "}");
			sprintf(m_charArrTmp, "m_data->%s(RawTimeToUnixTime(value));", field.fset.c_str());
		}
		else
		{
			// "3" -> 3
//			WriteWithNewLine("if(unlikely(!AllisDigit(value)))\n"
//							 "{\n"
//							 "\treturn false;\n"
//							 "}");
			sprintf(m_charArrTmp, "m_data->%s(stringToInt(value));",field.fset.c_str());
		}
	}
	else
	{
		sprintf(m_charArrTmp, "m_data->%s(value);", field.fset.c_str());
	}

	WriteWithNewLine(m_charArrTmp);

	WriteWithNewLine("break;");

	--m_nIdent;
	WriteWithNewLine("}");
	--m_nIdent;
}

void DataWappereGenerator::pub()
{
	m_nIdent = 0;
	WriteWithNewLine("public:");
	++m_nIdent;
}

void DataWappereGenerator::pri()
{
	m_nIdent = 0;
	WriteWithNewLine("private:");
	++m_nIdent;
}

void DataWappereGenerator::Variable()
{
	string tmp(m_msg.name);
	tmp.append(" *m_data;");
	WriteWithNewLine(tmp);

	WriteWithNewLine("string m_strSchema;");
	WriteWithNewLine("bool m_bOutData;");

	return;
}

void DataWappereGenerator::Write( string str)
{
	stringstream ss(str);
	string line;
	while(getline(ss, line))
	{
		for(unsigned i=0; i<m_nIdent; ++i)
		{
			m_dstFile << "\t";
		}

		m_dstFile << line;
	}

	return;
}

void DataWappereGenerator::WriteWithNewLine(string str)
{
	if(str.empty())
	{
		m_dstFile << endl;
		return;
	}

	stringstream ss(str);
	string line;
	while(getline(ss, line))
	{
		for(unsigned i=0; i<m_nIdent; ++i)
		{
			m_dstFile << "\t";
		}

		m_dstFile << line;
		m_dstFile << endl;
	}

	return;
}

string DataWappereGenerator::TextToCpp(string src)
{
	stringstream ss(src);
	string line;
	string out;
	while (getline(ss, line))
	{
		string outline("\"");

		for(auto const &c : line)
		{
			if(c == '\"')
			{
				outline.append("\\\"");
			}
			else if(c== '\r' || c == '\n')
			{
				outline.append("\\n");
			}
			else
			{
				outline.push_back(c);
			}
		}
		outline.append("\"\n");

		out.append(outline);
	}

	return out;
}

const JsonKey * DataWappereGenerator::GetJsonKeyWithName(string name)
{
	const JsonKey *pKey = nullptr;
	for(const JsonKey & key : m_msg.m_vecFields)
	{

		ToLowCase(name);

		if(name == key.fget)
		{
			pKey = &key;
			break;
		}
	}

	return pKey;
}

